# All the configuration settings for this Helm chart are shown below in this file. 
# This chart offers a default value for some of the settings, e.g. the commented out lines in this file.
replicaCount: 1

env: "prod"

timezone: "UTC"

image:
  repository: "quay.io/us-cdcgov/cdc-nbs-modernization/reporting-pipeline-service"
  tag: "v1.3.0"
# pullPolicy: IfNotPresent

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8081"

service:
  type: ClusterIP
  port: 8095

resources:
  limits:
    memory: "512Mi"
    cpu: "250m"
  requests:
    memory: "256Mi"
    cpu: "125m"

featureFlag:
  threadPoolSize: "1"
  elasticSearchEnable: "false"
  postProcessingEnable: "false"

probes:
  readiness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
#   periodSeconds: 10
  liveness:
    enabled: true
#   initialDelaySeconds: 60
#   periodSeconds: 30
#   failureThreshold: 5

jdbc:
  connection_url: "jdbc:sqlserver://EXAMPLE_DB_ENDPOINT:EXAMPLE_DB_PORT;databaseName=EXAMPLE_DB_NAME;encrypt=true;trustServerCertificate=true;"
  username: "EXAMPLE_DB_USERNAME"
  password: "EXAMPLE_DB_PASSWORD"

kafka:
  # e.g. for an AWS MSK provisioned cluster: b-<broker-id>.<cluster-name>.<unique-id>.c<cluster-number>.<aws-region>.amazonaws.com:<port>
  cluster: "EXAMPLE_KAFKA_ENDPOINT:EXAMPLE_KAFKA_PORT"
