apiVersion: v1
kind: Secret
metadata:
  name: reporting-pipeline-service-access
type: Opaque
# To create these secrets in your Kubernetes cluster, in your local copy of this file fill in your plaintext values for the secrets
# below and then do `kubectl apply -f nbs-secrets.yaml`, and then for security in this directory please
# do `git checkout nbs-secrets.yaml` to change your local copy of this file back to its contents from
# this GitHub repo. (Please do not check in unencrypted/plaintext secrets to Git!)
# Reference info: CDCgov/NEDSS-SystemAdminGuide/docs/4_initial_kubernetes_deployment/1_creating_kubernetes_secrets.md
stringData:
  # There is info about the following secrets at ../charts/reporting-pipeline-service/values.yaml
  db_connection_url: "jdbc:sqlserver://EXAMPLE_DB_HOSTNAME:1433;databaseName=EXAMPLE_DB_NAME;encrypt=false;trustServerCertificate=true;"
  db_user: "EXAMPLE_DB_USER"
  db_password: "EXAMPLE_DB_PASSWORD"
  kafka_cluster_url: "EXAMPLE_KAFKA_CLUSTER_URL"
