apiVersion: v2
name: real-time-reporting
description: Umbrella chart for Debezium, Kafka Connect, and Reporting Pipeline Service
type: application
version: 0.1.1
appVersion: "0.1.0"

dependencies:
  - name: debezium
    version: 0.0.3
    repository: file://charts/debezium
    condition: debezium.enabled
  - name: kafka-connect
    version: 0.1.1
    repository: file://charts/kafka-connect
    condition: kafka-connect.enabled
  - name: reporting-pipeline-service
    version: 1.3.2
    repository: file://charts/reporting-pipeline-service
    condition: reporting-pipeline-service.enabled
