apiVersion: v2
name: real-time-reporting
description: Umbrella chart for RTR Debezium, Kafka Connect sink, and Reporting Pipeline Service
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: debezium-rtr
    version: 0.0.2
    repository: file://../debezium
    condition: debezium-rtr.enabled
  - name: cp-kafka-connect
    version: 0.1.0
    repository: file://../kafka-connect-sink
    condition: cp-kafka-connect.enabled
  - name: reporting-pipeline-service
    version: 1.3.1
    repository: file://../reporting-pipeline-service
    condition: reporting-pipeline-service.enabled
