debezium-rtr:
  enabled: true
  connect:
    properties:
      bootstrap_server: "EXAMPLE_KAFKA_ENDPOINT"
    env:
      - name: BOOTSTRAP_SERVERS
        value: "EXAMPLE_KAFKA_ENDPOINT"

cp-kafka-connect:
  enabled: true
  kafka:
    bootstrapServers: "EXAMPLE_KAFKA_ENDPOINT"

reporting-pipeline-service:
  enabled: true
  kafka:
    cluster: "EXAMPLE_KAFKA_ENDPOINT"
  jdbc:
    connection_url: "jdbc:sqlserver://EXAMPLE_DB_ENDPOINT:1433;databaseName=rdb_modern;encrypt=true;trustServerCertificate=true;"
    username: "EXAMPLE_DB_USERNAME"
    password: "EXAMPLE_DB_PASSWORD"
  connectUrls:
    debezium:
      configMapName: debezium-rtr-connect
      key: DEBEZIUM_CONNECT_URL
    kafkaConnect:
      configMapName: cp-kafka-connect-sqlserver-connect
      key: KAFKA_CONNECT_URL
  startupDependencies:
    enabled: true
    image: curlimages/curl:8.8.0
    timeoutSeconds: 300
    pollIntervalSeconds: 5
    endpoints:
      debezium: "http://real-time-reporting-debezium-rtr-connect.<namespace>.svc.cluster.local:8083/connectors"
      kafkaConnect: "http://real-time-reporting-cp-kafka-connect.<namespace>.svc.cluster.local:8083/connectors"
