---
kafkaEndpoint: &kafkaEndpoint "kafka:29092"
dbEndpoint: &dbEndpoint "nbs-mssql"
dbName: &dbName "RDB"
dbUsername: &dbUsername "nbs_rdb"
dbPassword: &dbPassword "rdb"
dbPort: &dbPort "1433"

global:
  dbEndpoint: *dbEndpoint
  dbName: *dbName
  dbUsername: *dbUsername
  dbPassword: *dbPassword
  dbPort: *dbPort
  images:
    reportingPipelineService:
      repository: "nbs7-rtr-reporting-pipeline-service"
      tag: latest
      pullPolicy: Never

debezium-rtr:
  enabled: true
  connect:
    properties:
      bootstrap_server: *kafkaEndpoint
    env:
      - name: BOOTSTRAP_SERVERS
        value: *kafkaEndpoint

kafka-connect:
  enabled: true
  kafka:
    bootstrapServers: *kafkaEndpoint

reporting-pipeline-service:
  enabled: true
  featureFlag:
    threadPoolSize: "1"
    elasticSearchEnable: "false"
    postProcessingEnable: "false"
  kafka:
    cluster: *kafkaEndpoint
  jdbc:
    connection_url: "jdbc:sqlserver://{{ .Values.global.dbEndpoint }}:{{ .Values.global.dbPort }};databaseName={{ .Values.global.dbName }};encrypt=true;trustServerCertificate=true;"
    username: *dbUsername
    password: *dbPassword
  startupDependencies:
    enabled: true
    image: curlimages/curl:8.8.0
    timeoutSeconds: 300
    pollIntervalSeconds: 5
    endpoints:
      debezium: "http://real-time-reporting-debezium-rtr-connect.<namespace>.svc.cluster.local:8083/connectors"
      kafkaConnect: "http://real-time-reporting-kafka-connect.<namespace>.svc.cluster.local:8083/connectors"
