deployment:
  keycloak:
    env:
      kcDb: mssql
      kcDbPassword: "EXAMPLE_KCDB_PASS8675309"
      kcDbUrl: jdbc:sqlserver://EXAMPLE_DB_ENDPOINT:1433;databaseName=keycloak;encrypt=true;trustServerCertificate=true;
      kcDbUsername: NBS_keycloak
      kcHealthEnabled: "true"
      kcHostnameStrict: "false"
      kcHttpEnabled: "false"
      kcHttpRelativePath: /auth
      kcMetricsEnabled: "true"
      kcTransactionXaEnabled: "false"
      keycloakAdmin: admin
      keycloakAdminPassword: "EXAMPLE_KC_PASS8675309"
      kcProxyHeaders: xforwarded
    image:
      repository: quay.io/keycloak/keycloak
      tag: 26.6.6
  replicas: 1

# This can be used to load the theme
initContainers:
  enabled: true
  # The following tag/version is from https://hub.docker.com/_/alpine/tags
  image: "alpine:3.12"
  sleepDuration: 30 # in seconds
  #sleepDuration: "infinite" # This can be used for infinite sleep.
keycloak:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP

# Also part of the keycloak env vars:
kubernetesClusterDomain: cluster.local


# "aws" and "azure" are the supported values
cloudProvider: aws

# For Azure:
azure:
  files:
    storageRequest: 1Gi
    # Please see the commentary in ../elasticsearch/values.yaml about these values
    storageAccountName: "EXAMPLE_STORAGE_ACCOUNT_NAME"
    resourceGroupName: "EXAMPLE_RESOURCE_GROUP_NAME"

# For AWS:
pvc:
  kcPvClaim:
    storageClass: efs-kc
    storageRequest: 1Gi
efsFileSystemId: "EXAMPLE_EFS_ID"


probes:
  readiness:
    enabled: true
    #port: xxxx
    #initialDelaySeconds: xx
    #periodSeconds: xx
    #failureThreshold: x
  liveness:
    enabled: true
    #port: xxxx
    #initialDelaySeconds: xx
    #periodSeconds: xx
    #failureThreshold: x

resources:
  limits:
    memory: "1Gi"  
    cpu: "500m"      
  requests:
    memory: "512Mi"  
    cpu: "250m"
