# Used with official helm chart
controller:
  podAnnotations:
    linkerd.io/inject: enabled
  config:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    allow-snippet-annotations: "true"
    #proxy-body-size: "0"
  ingressClassResource:
    enabled: true
    default: false
  replicaCount: 1
  admissionWebhooks:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
      # service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-02064e56fdd565d67
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
      #prometheus.io/scheme: https
      prometheus.io/path: /metrics
    loadBalancerSourceRanges:
      - "10.70.0.0/16"  # Enter the CIDR range of the EKS VPC or pass it at run time as: controller.service.loadBalancerSourceRanges[0]
    # externalTrafficPolicy: Cluster