replicaCount: 1

env: "prod"

image:
  repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-compare-processor-service"
  pullPolicy: IfNotPresent
  tag: "v1.0.7"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8098"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8086
  httpsPort: 443


resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ingressHost: "data.EXAMPLE_DOMAIN"


# dbserver is passed in as an environment variable. It is just the database endpoint
jdbc:
  dbserver: ""
  username: ""
  password: ""

authUri: "http://keycloak.keycloak.svc.cluster.local/realms/NBS"

s3:
  bucketName: ""
  region: ""


# Note that some of these values are used by ./templates/deployment.yaml
azure:
  storageAccountName: "EXAMPLE_STORAGE_ACCOUNT_NAME"
  containerName: "EXAMPLE_CONTAINER_NAME"
  connectionString: "EXAMPLE_CONNECTION_STRING"
  sasToken: "EXAMPLE_SAS_TOKEN"
  managedIdentity:
    enabled: false

cloudProvider: aws

# For AWS:
pvc:
  dcPvClaim:
    storageClass: efs-datacompareprocessor
    storageRequest: 20Gi
efsFileSystemId: "EXAMPLE_EFS_ID"


ses:
  recipients: ""

kafka:
  cluster: "EXAMPLE_KAFKA_ENDPOINT"

log:
  path: "/usr/share/datacompareprocessor/data"
