apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka-connect.name" . }}-sqlserver-connect
  labels:
    app: {{ template "kafka-connect.name" . }}
    chart: {{ template "kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  KAFKA_CONNECT_URL: "http://{{ template "kafka-connect.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.servicePort }}"
  log4j.properties: |
    log4j.rootLogger={{ .Values.log_level }}, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n
