replicaCount: 1

image:
  repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-ingestion-service"
  pullPolicy: IfNotPresent
  tag: "v1.3.1"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8081"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8081
  httpsPort: 443

# An ingress is created for the following enabled services.
reportingService: # RTR
  enabled: "false"
  personReportingServicePort: 8091
  organizationReportingServicePort: 8092
  investigationReportingServicePort: 8093
  observationReportingServicePort: 8094
  postProcessingReportingServicePort: 8095
  ldfdataReportingServicePort: 8097
dataprocessingService: # data-processing-service - AKA Real Time Ingestion (RTI)
  enabled: "true"
  port: 8082
nndService: # nnd-service
  enabled: "false"
  port: 8081
caseNotification: # case-notification-service
  enabled: "true"
  port: 8093
compare: # data-compare-api-service
  # Note that when the reportingService.enabled value above is "false" then the following value should be "false" as well.
  enabled: "false"
  port: 8085

ingress:
  className: "nginx"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ingressHost: "data.EXAMPLE_DOMAIN"

# dbserver is just the database endpoint/hostname - not with the port number.
jdbc:
  dbserver: "EXAMPLE_DB_ENDPOINT"
  username: "EXAMPLE_ODSE_DB_USER"
  password: "EXAMPLE_ODSE_DB_USER_PASSWORD"

kafka:
  cluster: "EXAMPLE_MSK_KAFKA_ENDPOINTS"

log:
  path: "/usr/share/dataingestion/data"

# This can be set to "aws" or "azure".
cloudProvider: aws

#Azure PVC Settings#
azure:
  files:
    resourceGroupName: 
    storageAccountName: 
    storageClass: azurefile-csi-private-di
    storageRequest: 20Gi

#AWS PVC Settings#
pvc:
  diPvClaim:
    storageClass: efs-dataingestion
    storageRequest: 20Gi

# Only for AWS
efsFileSystemId: "EXAMPLE_EFS_ID"

# More info at: https://cdcgov.github.io/NEDSS-SystemAdminGuide/docs/deploy-nbs7/microservices-deployment/case-notification.html#keycloak-configuration
authUri: "http://keycloak.default.svc.cluster.local/auth/realms/NBS"

sftp:
  enabled: false
  host: "EXAMPLE_SFTP_HOST"
  username: "EXAMPLE_SFTP_USER"
  password: "EXAMPLE_SFTP_PASS"
  elrFileExtns: "EXAMPLE_SFTP_FILE_EXTNS" # e.g. "hl7,txt"
  filePaths: "EXAMPLE_SFTP_FILE_PATHS" # e.g. "/"
  # filePaths value should be comma seperated like "/,/LAB-1,/lab-2,/lab-2/lab2-sub-folder"

features:
  obrSplitting:
    enabled: false
  hl7BatchSplitting:
    enabled: false

apiPayloadMaxSize: "100MB"

# When this is set to "dev" then Swagger will be enabled and accessible via https://<data.EXAMPLE_DOMAIN>/ingestion/swagger-ui/index.html
springBootProfile: "dev"

# Override available for readiness and liveness probes: path, port, initialDelaySeconds, periodSeconds, failureThreshold
probes:
  readiness:
    enabled: true
  liveness:
    enabled: true

timezone: "UTC"
